[2025-02-11 13:31:26] [ERROR] log - Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_field.py", line 125, in render
    return str(field)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/widgets.py", line 279, in render
    return self._render(self.template_name, context, renderer)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/widgets.py", line 284, in _render
    return mark_safe(renderer.render(template_name, context))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/renderers.py", line 28, in render
    template = self.get_template(template_name)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 35, in get_template
    reraise(exc, self)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html
[2025-02-11 13:31:26] [ERROR] basehttp - "GET / HTTP/1.1" 500 354882
[2025-02-11 13:31:26] [ERROR] basehttp - "GET / HTTP/1.1" 500 354882
[2025-02-11 13:31:27] [ERROR] log - Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_utils.py", line 21, in render
    return remove_spaces(self.nodelist.render(context).strip())
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_field.py", line 125, in render
    return str(field)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/utils.py", line 79, in __str__
    return self.as_widget()
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 108, in as_widget
    return widget.render(
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/widgets.py", line 279, in render
    return self._render(self.template_name, context, renderer)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/widgets.py", line 284, in _render
    return mark_safe(renderer.render(template_name, context))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/renderers.py", line 28, in render
    template = self.get_template(template_name)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/forms/renderers.py", line 34, in get_template
    return self.engine.get_template(template_name)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 35, in get_template
    reraise(exc, self)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/crispy_forms/templatetags/crispy_forms_filters.py", line 61, in as_crispy_form
    return template.render(c)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/mnt/c/Users/Jorge/Desktop/iptvgestao-11-05/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: django_recaptcha/widget_v2_checkbox.html
[2025-02-11 13:31:27] [ERROR] basehttp - "GET / HTTP/1.1" 500 354686
[2025-02-11 13:31:27] [ERROR] basehttp - "GET / HTTP/1.1" 500 354686
